# Generated by Django 3.1.1 on 2020-10-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='correoe',
            new_name='email',
        ),
    ]
