# Generated by Django 3.1.1 on 2020-11-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_auto_20201025_1117'),
        ('compras', '0002_auto_20201028_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcompra',
            name='producto',
        ),
        migrations.AddField(
            model_name='dcompra',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.inventario'),
        ),
    ]
